name: Build, Push, Stop, and Cleanup Docker Container

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Create .env file from GitHub Secrets
      - name: Create .env file from GitHub Secrets
        run: |
          echo "Generating .env file..."
          echo "${{ secrets.APP_SECRET }}" >> .env
          cat .env

      # Load Environment Variables
      - name: Load Environment Variables
        run: |
          set -a
          source .env
          set +a
          echo "Using Docker Image Name: $DOCKER_IMAGE_NAME"

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          echo "Logged in to Docker Hub as ${{ secrets.DOCKER_USERNAME }}"

      # Build Docker Image
      - name: Build Docker Image
        run: |
          echo "Building Docker image..."
          docker build -f docker/Dockerfile.stage -t "$DOCKER_IMAGE_NAME:stage" .

      # Push Docker Image to Docker Hub
      - name: Push Docker Image
        run: |
          echo "Pushing image to Docker Hub..."
          docker push "$DOCKER_IMAGE_NAME:stage"

      # Print Deployment Instructions
      - name: Print Deployment Instructions
        run: |
          echo "================ Deployment Instructions ================"
          echo "To pull and run the image anywhere, use the following commands:"
          echo ""
          echo "1. Pull the latest image:"
          echo "   docker pull $DOCKER_IMAGE_NAME:stage"
          echo "2. Run the container:"
          echo "   docker run -p 8000:3000 --name appStage-container $DOCKER_IMAGE_NAME:stage"
          echo "========================================================="

  stop-and-cleanup:
    needs: build-and-push
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      # Load Environment Variables
      - name: Load Environment Variables
        run: |
          set -a
          source .env
          set +a
          echo "Using Docker Image Name: $DOCKER_IMAGE_NAME"

      # Stop and Remove Container
      - name: Stop and Remove Container
        run: |
          echo "Stopping container..."
          docker stop next15-container || echo "Container already stopped."

          echo "Removing container..."
          docker rm next15-container || echo "Container already removed."

      # Remove Docker Image
      - name: Remove Docker Image
        run: |
          echo "Removing Docker image..."
          docker rmi "$DOCKER_IMAGE_NAME:stage" || echo "Image already removed."
