name: Build and Push Docker Image

on:
  workflow_dispatch:  # Allows manual trigger from any branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    timeout-minutes: 120  # Automatically stop after 2 hours

    steps:
      - name: Restrict Execution to Repository Owner
        run: |
          if [[ "${{ github.actor }}" != "${{ github.repository_owner }}" ]]; then
            echo "Only the repository owner can run this workflow."
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create .env file from GitHub Secret
        run: |
          echo "${{ secrets.APP_SECRET }}" > .env
          cat .env  # Debug: Show contents of .env

      - name: Extract environment variables from .env
        run: |
          export $(grep -v '^#' .env | xargs)
          echo "DOCKER_USERNAME=$DOCKER_USERNAME"
          echo "DOCKER_CONTAINER_NAME=$DOCKER_CONTAINER_NAME"

      - name: Log in to Docker Hub
        run: |
          export $(grep -v '^#' .env | xargs)
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: Build Docker Image (Include .env in Image)
        run: |
          export $(grep -v '^#' .env | xargs)
          docker build -f docker/Dockerfile.stage \
            --build-arg DOCKER_CONTAINER_NAME="$DOCKER_CONTAINER_NAME" \
            --build-arg DOCKER_USERNAME="$DOCKER_USERNAME" \
            --build-arg DOCKER_PASSWORD="$DOCKER_PASSWORD" \
            -t "$DOCKER_CONTAINER_NAME":latest .

      - name: Push Docker Image
        run: |
          export $(grep -v '^#' .env | xargs)
          docker push "$DOCKER_CONTAINER_NAME":latest

      - name: Print Deployment Instructions
        run: |
          export $(grep -v '^#' .env | xargs)
          echo "================ Deployment Instructions ================"
          echo "To run this Docker container on another system, follow these steps:"
          echo ""
          echo "1. Ensure Docker is installed on your system."
          echo "2. Log in to Docker Hub (if required):"
          echo "   docker login -u \"$DOCKER_USERNAME\""
          echo "3. Pull the latest Docker image:"
          echo "   docker pull \"$DOCKER_CONTAINER_NAME\":latest"
          echo "4. Run the container:"
          echo "   docker run -d --name \"$DOCKER_CONTAINER_NAME\" -p 8000:8000 \"$DOCKER_CONTAINER_NAME\":latest"
          echo ""
          echo "Note: Modify the port mapping (-p 8000:8000) if needed."
          echo "========================================================="