name: Build and Push Docker Image

on:
  workflow_dispatch:  # Allows manual trigger from any branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create .env file from GitHub Secret (Hidden)
        run: |
          cat <<EOF > .env
          ${{ secrets.APP_SECRET }}
          EOF

      - name: Load and Export Environment Variables (Hidden)
        run: |
          set -a
          source .env || echo "Warning: Some variables may not have loaded properly"
          set +a

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image (Include .env in Image)
        run: |
          docker build -f docker/Dockerfile.stage \
            --build-arg DOCKER_CONTAINER_NAME="${{ secrets.DOCKER_CONTAINER_NAME }}" \
            --build-arg DOCKER_USERNAME="${{ secrets.DOCKER_USERNAME }}" \
            --build-arg DOCKER_PASSWORD="${{ secrets.DOCKER_PASSWORD }}" \
            -t "${{ secrets.DOCKER_CONTAINER_NAME }}":latest .

      - name: Push Docker Image
        run: |
          docker push "${{ secrets.DOCKER_CONTAINER_NAME }}":latest
